version: '3.9'

services:
  frontend:
    build:
        dockerfile: app-frontend/Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - api

  api:
    build:
        dockerfile: app-api/Dockerfile
    volumes:
      - ./credentials:/app/src/credentials
    env_file:
      - app-api/.env    
    ports:
      - 8001:8001