name: energy_forecasting_env

channels: 
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - poetry=1.3.2
  - twofish=0.3.0
  - pandas=1.5.3
  - tqdm=4.64.1
  - pip=23.0
  - pip:
    - hopsworks==3.0.5
    - category-encoders==2.6.0
    - fire==0.5.0
    - python-dotenv==0.21.1
    - yarl==1.8.2