name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]



jobs:
  deploy:
    env:
      CLOUDSDK_CORE_PROJECT: 'silver-device-379512'
      USER: 'pauliusztin'
      INSTANCE_NAME: 'ml-pipeline'
      ZONE: 'europe-west3-c'
  
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: '${{ env.CLOUDSDK_CORE_PROJECT }}'
          user: '${{ env.USER }}'
          instance_name: '${{ env.INSTANCE_NAME }}'
          zone: '${{ env.ZONE }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: >
            cd ~/energy-forecasting && 
            git pull && 
            sh deploy.sh
